import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";

export default function Home() {
  const  transactions  = api.transactions.getAllwithCodeAndVendor.useQuery();

  console.log(transactions.data)

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
      <div>
        {transactions.data?.map((transaction) => (<div key={transaction.id}>{transaction.transactionNumber} , {transaction.date.toUTCString()} , {transaction.vendor.description} , {transaction.gLCode.number} , {transaction.amount}</div>))}
      </div>
      </main>
    </>
  );
}
